# This workflow installs the dependencies and builds the code
name: build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install the dependencies
        run: npm install

      - name: Builds the code
        run: npm run build
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist