name: Validate commits

on:
  pull_request:
    paths:
        - "slides.md"
        - "pages/**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: validate-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/build.yml
